

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from xaibench.utils import RESULTS_DIR  # noqa: E402

METHODS = [("integrated_gradients", "Integrated Gradients"), ("lime", "LIME")]
K = 10
SPECIAL = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
           "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def escape(word):
    return "".join(SPECIAL.get(c, c) for c in word)


def coloured(words, scores, k):
    m = np.abs(scores).max() or 1.0
    top = set(np.argsort(-np.abs(scores), kind="stable")[:k])
    out = []
    for i, (w, s) in enumerate(zip(words, scores)):
        level = int(round(60 * abs(s) / m))           # 0-60% colour intensity
        colour = f"red!{level}" if s > 0 else f"blue!{level}"
        word = escape(w)
        if i in top:
            word = r"\underline{" + word + "}"
        out.append(r"\colorbox{" + colour + r"}{\strut " + word + "}" if level > 0 else word)
    return " ".join(out)


def main():
    path = RESULTS_DIR / "text" / "example_seed0.json"
    if not path.exists():
        raise SystemExit(f"{path} not found: run the text experiment first.")
    ex = json.load(open(path))
    words = ex["words"]
    label = "positive" if ex["y_pred"] == 1 else "negative"
    lines = [r"% Generated by scripts/fig_text.py -- requires \usepackage{xcolor}",
             r"{\setlength{\fboxsep}{0.8pt}\small",
             rf"\noindent\textbf{{Review}} (predicted {label}, $p = {ex['p_pred']:.2f}$, "
             rf"{len(words)} words).\par\medskip"]
    for key, title in METHODS:
        lines += [rf"\noindent\textbf{{{title}}}\par\smallskip",
                  r"\noindent " + coloured(words, np.array(ex[key], dtype=float), K) + r"\par\medskip"]
    lines.append("}")
    out = RESULTS_DIR / "figures"
    out.mkdir(parents=True, exist_ok=True)
    (out / "text_example.tex").write_text("\n".join(lines) + "\n")
    for key, title in METHODS:
        s = np.array(ex[key], dtype=float)
        top = [words[i] for i in np.argsort(-np.abs(s), kind="stable")[:K]]
        print(f"{title:22s} top-{K}: {', '.join(top)}")
    print(f"Written: {out / 'text_example.tex'}")


if __name__ == "__main__":
    main()
